# Set by github - do not change.
safe: true
lsi: false
highlighter: rouge

exclude:
- bower.json
- bower_components
- Gemfile
- Gemfile.lock

title: xenia
description: >
  xenia is a BSD licensed open source research project for emulating Xbox 360
  games on modern PCs.
baseurl:
url: "https://xenia.jp"
github_username:  xenia-project
patreon_username: xenia_project
twitter_username: xeniaproject
discord_invite: Q9mxZf9

markdown: kramdown

gems:
- jemoji
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap

navigation:
  - pages:
    - title: Home
      path: index.html
    - path: about.md
    - title: Quickstart
      url: https://github.com/xenia-project/xenia/wiki/Quickstart
      icon: assignment
    - title: FAQ
      url: https://github.com/xenia-project/xenia/wiki/faq
      icon: help
    - path: download.md
    - title: Roadmap
      url: https://github.com/xenia-project/xenia/wiki/roadmap
      icon: event
    - title: Compatibility
      url: https://github.com/xenia-project/game-compatibility/issues
      icon: insert_chart
    - path: gallery.html
  - title: Community
    pages:
    - title: Discord
      url: https://discord.gg/Q9mxZf9
      icon: message
    - title: /r/xenia
      url: https://www.reddit.com/r/xenia
      icon: forum
    - title: YouTube
      url: https://www.youtube.com/channel/UC6bJhkUUHE18HVG2mpbygSQ
      icon: videocam
#    - title: "#xenia @ freenode"
#      url: https://webchat.freenode.net/?channels=%23xenia
#      icon: people
  - title: Development
    pages:
    - title: Building
      url: https://github.com/xenia-project/xenia/blob/master/docs/building.md
      icon: build
    - title: Source Code
      url: https://github.com/xenia-project/xenia
      icon: code
    - title: Issues
      url: https://github.com/xenia-project/xenia/issues
      icon: bug_report
#    - title: Buildbot
#      url: https://build.xenia.jp/waterfall
#      icon: settings_system_daydream

artifacts:
  - title: Windows 7+ x64 (Direct3D 12 or Vulkan on Windows 10, Vulkan on Windows 7+)
    icon: windows
    branches:
    - name: master
      title: master
      download_url: "https://github.com/xenia-project/release-builds-windows/releases/latest/download/xenia_master.zip"
